# Generated by Django 5.2.1 on 2025-09-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_autor_options_alter_autor_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itenscompra',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
