# Generated by Django 5.2.1 on 2025-09-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_itenscompra_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
