# Generated by Django 5.2.1 on 2025-09-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_compra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
