# Generated by Django 5.2.1 on 2025-09-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_compra_data_atualizacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='data',
            new_name='data_criacao',
        ),
        migrations.AddField(
            model_name='compra',
            name='tipo_pagamento',
            field=models.IntegerField(choices=[(1, 'Cartão de Crédito'), (2, 'Cartão de Débito'), (3, 'PIX'), (4, 'Boleto'), (5, 'Transferência Bancária'), (6, 'Dinheiro'), (7, 'Outro')], default=1),
        ),
    ]
